/*opt_base_domain*/
INSERT INTO opt_base_domain (base_domain_id,api_name,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,enum_name,key_field,"name",response_field,"system",external_id) VALUES 
(5648,NULL,'N',-3,now(),now(),-3,'CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,'Court-Area','Court-Area','Court-Area',NULL,'BLF',NULL) on conflict do nothing;

/*opt_data_domain*/
INSERT INTO opt_data_domain (data_domain_id,application_type,archived,created_by,date_created,date_updated,updated_by,data_domain_type,description,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,"name",base_domain_id,external_id) VALUES 
(10000335,'1','N',-3,now(),now(),-3,NULL,'Court-Area','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,'Court-Area',5648,NULL) on conflict do nothing;

/*opt_data_domain_mapping*/
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001011,'N',-3,now(),now(),-3,'Add Onns','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,1,1,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001012,'N',-3,now(),now(),-3,'Additional Infromation','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,2,2,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001013,'N',-3,now(),now(),-3,'Calls','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,3,3,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001014,'N',-3,now(),now(),-3,'Contract Condition','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,4,4,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001015,'N',-3,now(),now(),-3,'Coverage','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,5,5,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001016,'N',-3,now(),now(),-3,'Credit Limit','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,6,6,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001017,'N',-3,now(),now(),-3,'Deactivation','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,7,7,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001018,'N',-3,now(),now(),-3,'Fraud','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,8,8,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001019,'N',-3,now(),now(),-3,'International Calls','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,9,9,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001020,'N',-3,now(),now(),-3,'Internet','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,10,10,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001021,'N',-3,now(),now(),-3,'Invoice','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,11,11,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001022,'N',-3,now(),now(),-3,'Payment','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,12,12,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001031,'N',-3,now(),now(),-3,'None','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,13,13,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001023,'N',-3,now(),now(),-3,'Other','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,14,14,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001024,'N',-3,now(),now(),-3,'Portability','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,15,15,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001025,'N',-3,now(),now(),-3,'Prepaid','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,16,16,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001026,'N',-3,now(),now(),-3,'Prorate','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,17,17,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001027,'N',-3,now(),now(),-3,'Roaming','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,18,18,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001028,'N',-3,now(),now(),-3,'Roaming Internet Limit','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,19,19,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001029,'N',-3,now(),now(),-3,'Roaming Welcome SMS','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,20,20,10000335,NULL,NULL) on conflict do nothing;
INSERT INTO opt_data_domain_mapping (data_domain_mapping_id,archived,created_by,date_created,date_updated,updated_by,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,sort_order,value,data_domain_id,external_id,value_char) VALUES 
(11001030,'N',-3,now(),now(),-3,'UDS','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,21,21,10000335,NULL,NULL) on conflict do nothing;
