/*BusinessProcessType*/

/*Case subType - id, name/descr,bpm flow, priority, severity, case type*/
INSERT INTO opt_business_process_type (business_process_type_id,archived,created_by,date_created,date_updated,updated_by,business_process_container_id,business_process_definition_id,business_process_domain,business_process_level,business_process_type_name,contact_medium_use_type,customer_display_value,default_priority,default_severity,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,is_internal,business_process_super_type_id,is_blocked_checkout,dep_ful_strat_id) VALUES 
(6974,'N',-3,now(),now(),-3,'optimacase','PPF_Case_SavingsRequestDisconnect','1','-1','Saving request due to disconnect',NULL,'eRecharge Revoke','high','High','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,false,6944,false,null) on conflict do nothing;

/*opt_process_type_map*/
INSERT INTO opt_process_type_map (process_type_map_id,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,businessprocesstypeid,entityspecid) VALUES
(50167,'N',-3, now(), now(),-3,'CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,true,6974,-42) on conflict do nothing;

/*opt_process_state*/
INSERT INTO opt_process_state (life_cycle_state_spec_id,archived,created_by,date_created,date_updated,updated_by,customer_display_value,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,is_internal,super_state,process_state_domain) VALUES 
(5238,'N',-3,now(), now(),-3,'Resolved','Offer Accepted','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,false,8,'CASE') on conflict do nothing;
INSERT INTO opt_process_state (life_cycle_state_spec_id,archived,created_by,date_created,date_updated,updated_by,customer_display_value,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_default,is_internal,super_state,process_state_domain) VALUES 
(5239,'N',-3,now(), now(),-3,'Resolved','Offer not Accepted','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,false,8,'CASE') on conflict do nothing;

/*opt_case_sla_definition*/
INSERT INTO opt_case_sla_definition (sla_id,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,sla_name,threshold_unit,threshold_value,time_unit,time_value) VALUES 
(570,'N',-3,now(),now(),-3,NULL,-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,'SLA_135hrs_THRESH_95hr','Hours',95,'Hours',135) on conflict do nothing;
INSERT INTO opt_case_sla_definition (sla_id,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,sla_name,threshold_unit,threshold_value,time_unit,time_value) VALUES 
(571,'N',-3,now(),now(),-3,NULL,-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,'SLA_243hrs_THRESH_170hr','Hours',170,'Hours',243) on conflict do nothing;

INSERT INTO opt_case_sla_definition (sla_id,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,sla_name,threshold_unit,threshold_value,time_unit,time_value) VALUES 
(572,'N',-3,now(),now(),-3,NULL,-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,'StateSLA_135hours','Hours',135,'Hours',135) on conflict do nothing;
INSERT INTO opt_case_sla_definition (sla_id,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,sla_name,threshold_unit,threshold_value,time_unit,time_value) VALUES 
(573,'N',-3,now(),now(),-3,NULL,-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,'StateSLA_198hours','Hours',198,'Hours',198) on conflict do nothing;

/*opt_characteristic*/
INSERT INTO opt_characteristic (characteristic_id,archived,created_by,date_created,date_updated,updated_by,category,characteristic_type,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,entity_name,"name",value_type,base_domain_id,external_id,validation_spec,data_domain_id,default_value,param_id,sort_order) VALUES 
(1000000180,'N',-3,now(),now(),-3,'Core-Attribute',NULL,'Preferred dispatched method','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,'Preferred dispatched method','Preferred dispatched method','2',NULL,'','',NULL,'',NULL,1) on conflict do nothing;
INSERT INTO opt_characteristic (characteristic_id,archived,created_by,date_created,date_updated,updated_by,category,characteristic_type,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,entity_name,"name",value_type,base_domain_id,external_id,validation_spec,data_domain_id,default_value,param_id,sort_order) VALUES 
(1000000182,'N',-3,now(),now(),-3,'Core-Attribute',NULL,'Email','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,'Email','Email','2',NULL,'','',NULL,'',NULL,2) on conflict do nothing;
INSERT INTO opt_characteristic (characteristic_id,archived,created_by,date_created,date_updated,updated_by,category,characteristic_type,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,entity_name,"name",value_type,base_domain_id,external_id,validation_spec,data_domain_id,default_value,param_id,sort_order) VALUES 
(1000000184,'N',-3,now(),now(),-3,'Core-Attribute',NULL,'Address','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,'Address','Address','2',NULL,'','',NULL,'',NULL,3) on conflict do nothing;
INSERT INTO opt_characteristic (characteristic_id,archived,created_by,date_created,date_updated,updated_by,category,characteristic_type,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,entity_name,"name",value_type,base_domain_id,external_id,validation_spec,data_domain_id,default_value,param_id,sort_order) VALUES 
(1000000186,'N',-3,now(),now(),-3,'Core-Attribute',NULL,'Contact number','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,'Contact number','Contact number','2',NULL,'','',NULL,'',NULL,4) on conflict do nothing;

/*opt_characteristic_use*/
INSERT INTO opt_characteristic_use (characteristic_use_id,archived,created_by,date_created,date_updated,updated_by,control_type,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_mandatory,priority,category_id,characteristic_id,data_domain_id,presentation_context_id,owner_type,product_template_id,customeraccount_template_id,cfs_template_id,product_group_type_id,process_action_id,default_value,is_editable,validation_spec,party_role_spec_id,external_id,entity_spec_id,characteristic_groups_id,is_displayed,presentation_component_id,is_policy,tooltip,contact_medium_spec_id,external_id_type_map_id,document_spec_id,port_request_type_id) VALUES 
(1000000180,'N',-3,now(),now(),-3,'1','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,true,1,NULL,1000000180,NULL,NULL,'PRESENTATION_CONTEXT',NULL,NULL,NULL,NULL,NULL,'',true,'',NULL,'',NULL,NULL,false,NULL,false,'',NULL,NULL,NULL,NULL) on conflict do nothing;
INSERT INTO opt_characteristic_use (characteristic_use_id,archived,created_by,date_created,date_updated,updated_by,control_type,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_mandatory,priority,category_id,characteristic_id,data_domain_id,presentation_context_id,owner_type,product_template_id,customeraccount_template_id,cfs_template_id,product_group_type_id,process_action_id,default_value,is_editable,validation_spec,party_role_spec_id,external_id,entity_spec_id,characteristic_groups_id,is_displayed,presentation_component_id,is_policy,tooltip,contact_medium_spec_id,external_id_type_map_id,document_spec_id,port_request_type_id) VALUES 
(1000000182,'N',-3,now(),now(),-3,'1','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,1,NULL,1000000182,NULL,NULL,'PRESENTATION_CONTEXT',NULL,NULL,NULL,NULL,NULL,'',true,'',NULL,'',NULL,NULL,false,NULL,false,'',NULL,NULL,NULL,NULL) on conflict do nothing;
INSERT INTO opt_characteristic_use (characteristic_use_id,archived,created_by,date_created,date_updated,updated_by,control_type,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_mandatory,priority,category_id,characteristic_id,data_domain_id,presentation_context_id,owner_type,product_template_id,customeraccount_template_id,cfs_template_id,product_group_type_id,process_action_id,default_value,is_editable,validation_spec,party_role_spec_id,external_id,entity_spec_id,characteristic_groups_id,is_displayed,presentation_component_id,is_policy,tooltip,contact_medium_spec_id,external_id_type_map_id,document_spec_id,port_request_type_id) VALUES 
(1000000184,'N',-3,now(),now(),-3,'1','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,false,1,NULL,1000000184,NULL,NULL,'PRESENTATION_CONTEXT',NULL,NULL,NULL,NULL,NULL,'',true,'',NULL,'',NULL,NULL,false,NULL,false,'',NULL,NULL,NULL,NULL) on conflict do nothing;
INSERT INTO opt_characteristic_use (characteristic_use_id,archived,created_by,date_created,date_updated,updated_by,control_type,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,is_mandatory,priority,category_id,characteristic_id,data_domain_id,presentation_context_id,owner_type,product_template_id,customeraccount_template_id,cfs_template_id,product_group_type_id,process_action_id,default_value,is_editable,validation_spec,party_role_spec_id,external_id,entity_spec_id,characteristic_groups_id,is_displayed,presentation_component_id,is_policy,tooltip,contact_medium_spec_id,external_id_type_map_id,document_spec_id,port_request_type_id) VALUES 
(1000000186,'N',-3,now(),now(),-3,'1','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,true,1,NULL,1000000186,NULL,NULL,'PRESENTATION_CONTEXT',NULL,NULL,NULL,NULL,NULL,'',true,'',NULL,'',NULL,NULL,false,NULL,false,'',NULL,NULL,NULL,NULL) on conflict do nothing;

/*opt_process_type_template*/
INSERT INTO opt_process_type_template (process_type_template_id,archived,created_by,date_created,date_updated,updated_by,channel,description,display_value,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,sort_order,process_state,process_sub_type,process_type,log_history,default_template_visibilty) VALUES 
(645,'N',-3,now(),now(),-3,'7','Itemized bill for past period','Itemized bill for past period','CONFIRMED',-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,1,5127,6974,6944,true,'EDITABLE') on conflict do nothing;

/*opt_process_type_template_characteristic_use*/
/*589*/
INSERT INTO opt_process_type_template_characteristic_use (process_type_template_characteristic_use_id,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,characteristic_use_id,process_type_template_id) VALUES 
(2696,'N',-3,now(),now(),-3,NULL,-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,1000000180,645) on conflict do nothing;
INSERT INTO opt_process_type_template_characteristic_use (process_type_template_characteristic_use_id,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,characteristic_use_id,process_type_template_id) VALUES 
(2697,'N',-3,now(),now(),-3,NULL,-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,1000000182,645) on conflict do nothing;
INSERT INTO opt_process_type_template_characteristic_use (process_type_template_characteristic_use_id,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,characteristic_use_id,process_type_template_id) VALUES 
(2698,'N',-3,now(),now(),-3,NULL,-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,1000000184,645) on conflict do nothing;
INSERT INTO opt_process_type_template_characteristic_use (process_type_template_characteristic_use_id,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,characteristic_use_id,process_type_template_id) VALUES 
(2699,'N',-3,now(),now(),-3,NULL,-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,1000000186,645) on conflict do nothing;

/*opt_process_type_template_channel*/
INSERT INTO opt_process_type_template_channel (process_type_template_channel_id,archived,created_by,date_created,date_updated,updated_by,channel,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,process_type_template_id) VALUES 
(436,NULL,NULL,now(),now(),NULL,'14',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,645) on conflict do nothing;
INSERT INTO opt_process_type_template_channel (process_type_template_channel_id,archived,created_by,date_created,date_updated,updated_by,channel,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,process_type_template_id) VALUES 
(437,NULL,NULL,now(),now(),NULL,'7',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,645) on conflict do nothing;
INSERT INTO opt_process_type_template_channel (process_type_template_channel_id,archived,created_by,date_created,date_updated,updated_by,channel,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,process_type_template_id) VALUES 
(438,NULL,NULL,now(),now(),NULL,'27',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,645) on conflict do nothing;

/*Translation*/
INSERT INTO blc_translation (translation_id,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,site_disc,entity_id,entity_type,field_name,locale_code,translated_value) VALUES 
(55000,'N',-3,now(),now(),-3,NULL,-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,NULL,'6974','BusinessProcessType','businessProcessTypeName','bg_BG','Заявка за запазване при отказ от услуга') on conflict do nothing;
INSERT INTO blc_translation (translation_id,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,site_disc,entity_id,entity_type,field_name,locale_code,translated_value) VALUES 
(55001,'N',-3,now(),now(),-3,NULL,-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,NULL,'6974','BusinessProcessType','customerDisplayValue','bg_BG','Заявка за запазване при отказ от услуга') on conflict do nothing;
INSERT INTO blc_translation (translation_id,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,site_disc,entity_id,entity_type,field_name,locale_code,translated_value) VALUES 
(55002,'N',-3,now(),now(),-3,NULL,-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,NULL,'1000000180','Characteristic','displayValue','bg_BG','Предпочитан начин на получаване') on conflict do nothing;
INSERT INTO blc_translation (translation_id,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,site_disc,entity_id,entity_type,field_name,locale_code,translated_value) VALUES 
(55003,'N',-3,now(),now(),-3,NULL,-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,NULL,'1000000182','Characteristic','displayValue','bg_BG','Електронна поща') on conflict do nothing;
INSERT INTO blc_translation (translation_id,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,site_disc,entity_id,entity_type,field_name,locale_code,translated_value) VALUES 
(55004,'N',-3,now(),now(),-3,NULL,-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,NULL,'1000000184','Characteristic','displayValue','bg_BG','Адрес') on conflict do nothing;
INSERT INTO blc_translation (translation_id,archived,created_by,date_created,date_updated,updated_by,admin_addition_status,catalog_disc,sndbx_catalog_flag,sndbx_orig_item_id,sndbx_orig_record_id,sndbx_id,sndbx_archived_flag,sndbx_deleted_flag,sndbx_tmplt_record_id,sndbx_tier,site_disc,entity_id,entity_type,field_name,locale_code,translated_value) VALUES 
(55005,'N',-3,now(),now(),-3,NULL,-2,-3,NULL,NULL,NULL,'N','N',NULL,NULL,NULL,'1000000186','Characteristic','displayValue','bg_BG','Номер за контакт') on conflict do nothing;
